# version: "3"
services:

  frontend:
    # container_name: blm-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:3000"  #"3000:3000"
    restart: always

  nginx:
    image: nginx:alpine
    # container_name: blm-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend 
    restart: always


